export const FETCH_PLANT = "ACTION_FETCH_PLANT";
export const PLANT_RECIEVED = "ACTION_PLANT_RECIEVED";
export const FETCH_PLANTS = "ACTION_FETCH_PLANTS";
export const PLANTS_RECIEVED = "ACTION_PLANTS_RECIEVED";
export const POST_CONTACT = "ACTION_POST_CONTACT";
