export const GET_PLANT = "ACTION_GET_PLANT";
export const PLANT_RECIEVED = "ACTION_PLANT_RECIEVED";
export const GET_PLANTS = "ACTION_GET_PLANTS";
export const PLANTS_RECIEVED = "ACTION_PLANTS_RECIEVED";
export const POST_CONTACT = "ACTION_POST_CONTACT";
